export enum JanusRequestEvent {
  CREATE = 'create',
  DESTROY = 'destroy',
  EDIT = 'edit',
  EXISTS = 'exists',
  LIST = 'list',
  ALLOWED = 'allowed',
  KICK = 'kick',
  MODERATE = 'moderate',
  ENABLE_RECORDING = 'enable_recording',
  LISTPARTICIPANTS = 'listparticipants',
  LISTFORWARDERS = 'listforwarders',
  JOIN = 'join',
  JOINANDCONFIGURE = 'joinandconfigure',
  CONFIGURE = 'configure',
  PUBLISH = 'publish',
  UNPUBLISH = 'unpublish',
  START = 'start',
  PAUSE = 'pause',
  SWITCH = 'switch',
  LEAVE = 'leave',
}
