export enum NotificationType {
  COMMENT = 'COMMENT',
  COMMENT_COMMENT = 'COMMENT_COMMENT',
  COMMENT_MENTION = 'COMMENT_COMMENT_MENTION',
  DM = 'DM',
  REQUESTED_FRIEND = 'REQUESTED_FRIEND',
  RECEIVED_FRIEND = 'RECEIVED_FRIEND',
  INVITED_GAME = 'INVITED_GAME',
  SYSTEM = 'SYSTEM',
}
